# Generated by Django 5.1.5 on 2025-02-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='calibration_due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='last_calibration_date',
            field=models.DateTimeField(),
        ),
    ]
