# Generated by Django 5.1.5 on 2025-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_alter_calibrationlog_calibrated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='Is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
